[package]
name = "jwt-validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
jwt-core = { path = "core" }
jwt-methods = { path = "methods" }
# risc0-zkvm = { path = "../../risc0/zkvm" }
risc0-zkvm = { git = "https://github.com/risc0/risc0" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]

[patch.crates-io]
# TODO: Make a permanent `rsa` patch
rsa = { git = "https://www.github.com/risc0/RustCrypto-RSA.git", rev = "aa73b77db01cf407fa4521faffbf5408bf274e1a" }
