[package]
name = "jwt-validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
jwt-core = { path = "core" }
jwt-methods = { path = "methods" }
risc0-zkvm = { git = "https://github.com/risc0/risc0" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]

[patch.crates-io]
rsa = { git = "https://www.github.com/risc0/RustCrypto-RSA.git", rev = "555416ebe2f3d013aae4b609dbacc4a2026b0a17" }
