[package]
name = "prover-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
risc0-zkvm-methods = { path = "../../risc0/zkvm/methods" }
risc0-zkvm = { path = "../../risc0/zkvm", features = ["unstable"] }
risc0-circuit-keccak = { path = "../../risc0/circuit/keccak" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
workerpool = "1.2"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
