[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
jwt-core = { path = "../../core/" }
risc0-circuit-bigint = { path = "../../../../risc0/circuit/bigint", default-features = false, features = [ "unstable" ] }
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = ["std"] }

[patch.crates-io]
rsa = { path = "/Users/tzerrell/code/RustCrypto/RSA" }
