[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
jwt-core = { path = "../../core/" }
# risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = ["std"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", default-features = false, features = ["std"] }

[patch.crates-io]
# TODO: Make a permanent `rsa` patch
rsa = { git = "https://www.github.com/risc0/RustCrypto-RSA.git", rev = "aa73b77db01cf407fa4521faffbf5408bf274e1a" }
