[package]
name = "risc0-zkvm-methods"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
c-kzg = { git = "https://github.com/risc0/c-kzg-4844.git", rev = "304eacb4f5fec09e837936e4ada6705ecac581f0", default-features = false, features = [
    "std"
], optional = true }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["guest", "rand", "std", "cpp-crates", "c-kzg"]

[dependencies]
risc0-zkvm = { workspace = true }
risc0-zkvm-platform = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
c-kzg = ["dep:c-kzg"]
