[package]
name = "jwt-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
# risc0-build = { path = "../../../risc0/build" }
risc0-build = { git = "https://github.com/risc0/risc0" }

[package.metadata.risc0]
methods = ["guest"]
