[package]
name = "rzup"
description = "The RISC Zero version management library and CLI"
version = "0.3.0-alpha.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[[bin]]
name = "rzup"
path = "src/bin/rzup.rs"
required-features = ["cli"] # check this

[features]
default = ["cli"] # and this
cli = ["dep:clap"]

[dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
thiserror = "2.0.7"
dirs = "5.0.1"
tempfile = "3.14.0"
semver = "1.0.24"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

# cli dependencies
clap = { version = "4.5.23", features = ["derive"], optional = true }
downloader = { version = "0.2.8", default-features = false, features = ["rustls-tls"] }
flate2 = "1.0.35"
xz = "0.1.0"
fs2 = "0.4.3"
fs_extra = "1.3.0"
tar = "0.4.43"
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "blocking", "json"] }

# TEMP
# [lints.rust]
# dead_code = "allow"
# unused_variables = "allow"
