cache = true
exclude_all_private = true
exclude_path = ["./build", "./node_modules"]
max_cache_age = "10d"
max_redirects = 10
max_retries = 3

exclude = [
  # rate limited & forbidden 403
  "siam.org",
  "basescan.org",
  "arbiscan.io",
  "theblock.co",
  "hackenproof.com",
]
